BackOffice/Areas/Clients/Controllers/ViewController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BackOffice.Areas.Clients.Models;
using Core.Clients;
using LkeServices.Clients;

namespace BackOffice.Areas.Clients.Controllers
{
    [Authorize]
    public class ViewController : Controller
    {
        private readonly SrvClientFinder _srvClientFinder;
        private readonly IClientsSessionsRepository _clientsSessionsRepository;

        public ViewController(SrvClientFinder srvClientFinder, IClientsSessionsRepository clientsSessionsRepository)
        {
            _srvClientFinder = srvClientFinder;
            _clientsSessionsRepository = clientsSessionsRepository;
        }

        [HttpPost]
        public ActionResult Index()
        {
            var viewModel = new ClientViewIndexVideModel
            {
                RequestUrl = Url.Action("Find")
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Find(string phrase)
        {
            var viewModel = new ClientViewFindViewModel
            {
                PersonalData = await _srvClientFinder.FindClientAsync(phrase),
                
            };

            if (viewModel.PersonalData == null)
                return View(viewModel);

            viewModel.Sessions =
                (await _clientsSessionsRepository.GetByClientAsync(viewModel.PersonalData.Id)).ToArray();

            return View(viewModel);
        }
    }
}

BackOffice/Areas/Dictionaries/Controllers/AssetsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BackOffice.Areas.Dictionaries.Models;
using BackOffice.Controllers;
using BackOffice.Translates;
using Core.Assets;

namespace BackOffice.Areas.Dictionaries.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {
        private readonly IAssetsRepository _assetsRepository;

        public AssetsController(IAssetsRepository assetsRepository)
        {
            _assetsRepository = assetsRepository;
        }


        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var viewModel = new AssetsIndexViewModel
            {
                Assets = await _assetsRepository.GetAssetsAsync()
            };

            return View(viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> EditAssetDialog(string id)
        {
            var viewModel = new EditAssetDialogViewModel
            {
                Caption = Phrases.EditAsset,
                Asset = string.IsNullOrEmpty(id) ? Asset.CreateDefault() : await _assetsRepository.GetAssetAsync(id)
            };

            return View(viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> EditAsset(EditAssetModel model)
        {

            if (string.IsNullOrEmpty(model.Id))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#id");

            if (string.IsNullOrEmpty(model.Name))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#name");


            if (string.IsNullOrEmpty(model.EditId) || model.EditId != model.Id)
            {
                if (await _assetsRepository.GetAssetAsync(model.Id) != null)
                    return this.JsonFailResult(Phrases.AssetWithSameIdExists, "#id");
            }

            if (string.IsNullOrEmpty(model.EditId))
                await _assetsRepository.RegisterAssetAsync(model);
            else
                await _assetsRepository.EditAssetAsync(model.EditId, model);

            return this.JsonRequestResult("#pamain", Url.Action("Index"));
        }

    }
}

BackOffice/Areas/Kyc/Controllers/DocumentsCheckingController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BackOffice.Areas.Kyc.Models;
using BackOffice.Controllers;
using BackOffice.Translates;
using Core.Clients;
using Core.Kyc;
using LkeServices.Clients;
using LkeServices.Kyc;

namespace BackOffice.Areas.Kyc.Controllers
{
    [Authorize]
    public class DocumentsCheckingController : Controller
    {
        private readonly SrvKycStatusManager _kycStatusManager;
        private readonly SrvClientFinder _srvClientFinder;
        private readonly IPersonalDataRepository _personalDataRepository;
        private readonly IKycRepository _kycRepository;

        public DocumentsCheckingController(SrvKycStatusManager kycStatusManager, SrvClientFinder srvClientFinder, 
            IPersonalDataRepository personalDataRepository, IKycRepository kycRepository)
        {
            _kycStatusManager = kycStatusManager;
            _srvClientFinder = srvClientFinder;
            _personalDataRepository = personalDataRepository;
            _kycRepository = kycRepository;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var viewModel = new DocumentsCheckingIndexViewModel
            {
                ClientAccounts = await _kycStatusManager.GetAccountsToCheck(),
                RequestUrl = Url.Action("FindClient")
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> FindClient(string phrase)
        {
            var viewModel = new DocumentsCheckingFindClientViewModel
            {
                PersonalData = await _srvClientFinder.FindClientAsync(phrase)
            };

            if (viewModel.PersonalData == null)
                return View(viewModel);

            viewModel.KycStatus = await _kycRepository.GetKycStatusAsync(viewModel.PersonalData.Id);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Change(UpdateDocumentsAndStatusModel data)
        {
            await _personalDataRepository.UpdateAsync(data);
            await _kycStatusManager.ChangeKycStatus(data.Id, data.KycStatus);
            return this.JsonRequestResult("#pamain", Url.Action("Index"));
        }


    }
}

BackOffice/Areas/Users/Controllers/ManagementController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BackOffice.Areas.Users.Models;
using BackOffice.Controllers;
using BackOffice.Translates;
using Core;

namespace BackOffice.Areas.Users.Controllers
{
    [Authorize]
    public class ManagementController : Controller
    {
        private readonly IBackOfficeUsersRepository _backOfficeUsersRepository;

        public ManagementController(IBackOfficeUsersRepository backOfficeUsersRepository)
        {
            _backOfficeUsersRepository = backOfficeUsersRepository;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var viewModel = new UsersManagementIndexViewModel
            {
                Users = await _backOfficeUsersRepository.GetAllAsync()
            };

            return View(viewModel);
        }



        [HttpPost]
        public async Task<ActionResult> EditUserDialog(string id)
        {
            var viewModel = new EditUserDialogViewModel
            {
                User = string.IsNullOrEmpty(id) ? BackOfficeUser.CreateDefault():  await _backOfficeUsersRepository.GetAsync(id),
                Caption = Phrases.EditUser
            };

            return View(viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> EditUser(EditUserModel model)
        {
            if (string.IsNullOrEmpty(model.Id))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#id");

            if (string.IsNullOrEmpty(model.FullName))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#fullName");

            if (string.IsNullOrEmpty(model.Password))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#password");

            if (!string.IsNullOrEmpty(model.Create))
            {
                if (await _backOfficeUsersRepository.UserExists(model.Id))
                    return this.JsonFailResult(Phrases.UserExists, "#id");
            }

            await _backOfficeUsersRepository.SaveAsync(model, model.Password);

            return this.JsonRequestResult("#pamain", Url.Action("Index"));

        }

    }

}

BackOffice/Controllers/BackOfficeController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.BackOffice;

namespace BackOffice.Controllers
{
    [Authorize]
    public class BackOfficeController : Controller
    {
        private readonly IMenuBadgesRepository _menuBadgesRepository;

        public BackOfficeController(IMenuBadgesRepository menuBadgesRepository)
        {
            _menuBadgesRepository = menuBadgesRepository;
        }

        [HttpPost]
        public ActionResult Layout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Menu()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetBadges()
        {
            var badges = await _menuBadgesRepository.GetBadesAsync();
            return Json(badges.Select(itm => new {id = itm.Id, value = itm.Value}));
        }

    }
}

BackOffice/Views/BackOffice/Layout.cshtml
@model dynamic

@{
    Layout = null;
}

<nav class="navigation-pinned" style="position: absolute;background-color: #3A3633;">
    <div id="menuwrapper" class="menuwrapper" data-autoheight="0">
        <script>
            Requests.doRequest({ url: '@Url.Action("Menu")', divResult: '#menuwrapper' })
        </script>
    </div>

</nav>
<section id="pamain" data-autoheight="0" data-autowidth="-200" style="overflow-y: auto; background: white;position: absolute;top: 0;left: 200px;-webkit-user-select: initial;"></section>
<div id="modalBackground" onclick="Ui.hideDialog()" style="position: fixed; z-index: 10000; left:200px; top:0;background: rgba(0, 0, 0, 0.8); display: none; " data-autowidth="-200" data-autoheight="0">
    <table style="width: 100%; height: 100%">
        <tr>
            <td>
                <div id="modalData" onclick="event.stopPropagation()">

                </div>
            </td>
        </tr>

    </table>

</div>

BackOffice/Views/BackOffice/Layout.mobile.cshtml
@{
    Layout = null;
}

<script>
    $('#btnMnu').show();

    Requests.doRequest({ url: '@Url.Action("Menu")', divResult: '#mnuContent' });
    ui.menuClick();
</script>

BackOffice/Views/BackOffice/Menu.cshtml
@model BackOffice.Models.MainMenuViewModel

@{
    Layout = null;
}


<div>
    <div style="text-align: center; font-size: 9px;">
        <span id="srvTime" style="color: white; text-align: right;"></span>
    </div>
    <img src="~/Images/logo-white.png" style="padding: 5px; width: 100%;" />
</div>
<hr style="border-bottom: 1px solid #080606; margin: 5px 36px 0 5px;" />


<div id="wrapper" data-autoheight="-74" style="position: absolute; overflow: hidden">
    @Html.Partial("PartialMenu", Model)
</div>
<script>

    $('.smi').each(function() {
        $(this).html($(this).attr('data-text'));
        $(this).click(menuItemClick);
    });

    var activeItem;

    function menuItemClick() {

        if (activeItem)
            activeItem.removeClass('smiSel');

        activeItem = $(this);
        var url = activeItem.attr('data-url');


        if (url) {
            $('#pamain').html('<div style="text-align:center; margin-top:20px;"><img src="/Images/Loading-pa.gif"/></div>');
            var options = { url: url, type: 'POST' };
            $.ajax(options)
                .then(function(result) {
                    activeItem.addClass('smiSel');
                    $('#pamain').html(result);
                    layout.ressize();
                }).fail(function(fr) {
                    activeItem.addClass('smiSel');
                    $('#pamain').html(fr.responseText);
                });
        } else {
            $('#pamain').html('<h1>No content</h1>');
            activeItem.addClass('smiSel');
        }

    }


    $('#wrapper').perfectScrollbar({
        wheelSpeed: 20,
        wheelPropagation: false
    });



    window.setInterval(RefreshBadges, 5000);

    function RefreshBadges() {
        var options = { url: '@Url.Action("GetBadges")', type: 'POST' };
        $.ajax(options)

               .then(function (result) {

                   //$('#srvTime').html(result.Time);

                   result.forEach(function (itm) {
                       var node = $('#smi' + itm.id);
                       console.log(node);
                       console.log(itm.value);
                       if (itm.value === "0")
                           node.html(node.attr('data-text'));
                       else
                           node.html(node.attr('data-text') + ' <span class="badge" style="background:red; font-size:9px;padding: 1px 5px 2px 4px;">' + itm.value + "</span>");
                   });

               }).fail(function (fr) {


               });
    }
    RefreshBadges();


</script>

BackOffice/Views/BackOffice/Menu.mobile.cshtml
@model BackOffice.Models.MainMenuViewModel
@{
    Layout = null;
}

@Html.Partial("PartialMenu", Model)

<script>
    $('.smi').each(function () {
        $(this).html($(this).attr('data-text'));
        $(this).click(menuItemClick);
    });
    var activeItem;
    function menuItemClick() {

        if (activeItem)
            activeItem.removeClass('smiSel');

        activeItem = $(this);
        var url = activeItem.attr('data-url');


        if (url) {
            $('#pamain').html('<div style="text-align:center; margin-top:20px;"><img src="/Images/Loading-pa.gif"/></div>');
            var options = { url: url, type: 'POST' };
            $.ajax(options)
                .then(function (result) {
                    activeItem.addClass('smiSel');
                    $('#pamain').html(result);
                    layout.ressize();
                }).fail(function (fr) {
                    activeItem.addClass('smiSel');
                    $('#pamain').html(fr.responseText);
                });
        } else {
            $('#pamain').html('<h1>No content</h1>');
            activeItem.addClass('smiSel');
        }

    }

</script>

BackOffice/Views/BackOffice/PartialMenu.cshtml
@using BackOffice.Translates
@using Core.BackOffice
@model BackOffice.Models.MainMenuViewModel
@{
    Layout = null;
}

<ul class="sidemenu" style="width: 201px;">
    <li class="smi" data-url="@Url.Action("Index", "ChangeMyPassword", new {area = "Users"})" data-text="@Phrases.ChangeMyPassword"></li>
    <li id="smi@(MenuBadges.Kyc)" class="smi" data-url="@Url.Action("Index", "DocumentsChecking", new {area = "Kyc"})" data-text="KYC"></li>
    <li class="smi" data-url="@Url.Action("Index", "View", new {area = "Clients"})" data-text="@Phrases.Clients"></li>
    <li class="smi" data-url="@Url.Action("Index", "Registrations", new {area = "EventLogs"})" data-text="@Phrases.Registrations"></li>


    <li class="smi" data-url="@Url.Action("Index", "Assets", new {area = "Dictionaries"})" data-text="@Phrases.DictionaryAssets"></li>
    <li class="smi smiSub" data-url="@Url.Action("Index", "AssetPairs", new {area = "Dictionaries"})" data-text="@Phrases.DictionaryAssetPairs"></li>

    <li class="smi" data-url="@Url.Action("Index", "Management" , new {area="Users" })" data-text="@Phrases.Users"></li>
</ul>