BackOffice/Areas/Clients/Controllers/SessionsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BackOffice.Areas.Clients.Models;
using BackOffice.Controllers;
using BackOffice.Translates;
using Core.Clients;

namespace BackOffice.Areas.Clients.Controllers
{
    [Authorize]
    public class SessionsController : Controller
    {
        private readonly IClientsSessionsRepository _clientsSessionsRepository;

        public SessionsController(IClientsSessionsRepository clientsSessionsRepository)
        {
            _clientsSessionsRepository = clientsSessionsRepository;
        }

        [HttpPost]
        public ActionResult DeleteConfirmationDialog(DeleteSessionModel model)
        {
            var viewModel = new DeleteSessionConfirmationDialogViewModel
            {
                Caption = Phrases.PleaseConfirmYourAction,
                Data = model
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteSession(DeleteSessionModel model)
        {
            await _clientsSessionsRepository.DeleteSessionAsync(model.ClientId, model.Token);
            return this.JsonResultShowDialog(Url.Action("DeletedDialog"));
        }

        [HttpPost]
        public ActionResult DeletedDialog()
        {
            var viewModel = new SessionDeletedDialogViewModel
            {
                Caption = Phrases.SessionHasBeenDeleted
            };


            return View(viewModel);
        }
    }
}

BackOffice/Areas/Clients/Views/View/Find.cshtml
@using BackOffice.Translates
@using Core.Clients
@model BackOffice.Areas.Clients.Models.ClientViewFindViewModel

@{
    Layout = null;

    if (Model.PersonalData == null)
    {
        <h1>@Phrases.ClientNotFound</h1>
        return;
    }
}

<h3>Client Id: @Model.PersonalData.Id</h3>
<h3>Email: @Model.PersonalData.Email</h3>
<h3>FullName: @Model.PersonalData.FullName</h3>


@RenderClientSessions(Model.Sessions)

@helper RenderClientSessions(IClientSession[] sessions)
{

    <table class="table" style="width: 80%; margin: auto">
        <tr>
            <th>
                @Phrases.Date
            </th>
            <th>
                @Phrases.LastAction
            </th>
            <th>
                @Phrases.Device
            </th>
            <th>

            </th>
        </tr>


        @foreach (var clientSession in sessions)
        {
            <tr>
                <td>
                    @clientSession.Registered
                </td>
                <td>
                    @clientSession.LastAction
                </td>
                <td>
                    @clientSession.ClientInfo
                </td>
                <td>
                    <button class="btn btn-xs btn-primary"
                            onclick="ui.showDialog('@Url.Action("DeleteConfirmationDialog","Sessions", new {area="Clients"})', {ClientId:'@clientSession.ClientId', Token:'@clientSession.Token'})">@Phrases.KickSession</button>
                </td>
            </tr>
        }
    </table>
}

BackOffice/Areas/Clients/Views/View/Index.cshtml
@model BackOffice.Areas.Clients.Models.ClientViewIndexVideModel

@{
    Layout = null;
}
<div style="width: 400px;">
@Html.Partial("PartialFindCleint", Model)
    
</div>


<div id="foundClient">
    
</div>