LykkeWallet/Areas/Accounts/Controllers/ListController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Accounts;
using LykkeWallet.Areas.Accounts.Models;
using LykkeWallet.Controllers;

namespace LykkeWallet.Areas.Accounts.Controllers
{
    [Authorize]
    public class ListController : Controller
    {
        private readonly IAccountsRepository _accountsRepository;

        public ListController(IAccountsRepository accountsRepository)
        {
            _accountsRepository = accountsRepository;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var kycResult = await this.GetKycStatus();
            if (kycResult != null)
                return kycResult;

            var clientId = this.GetClientId();

            var viewModel = new AccountsIndexViewModel
            {
                Accounts = await _accountsRepository.GetAccountsAsync(clientId)
            };

            return View(viewModel);
        }
    }
}

LykkeWallet/Areas/Exchange/Controllers/AssetsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Accounts;
using LykkeWallet.Areas.Exchange.Models;
using LykkeWallet.Controllers;

namespace LykkeWallet.Areas.Exchange.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {
        private readonly IAccountsRepository _accountsRepository;

        public AssetsController(IAccountsRepository accountsRepository)
        {
            _accountsRepository = accountsRepository;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var kycResult = await this.GetKycStatus();
            if (kycResult != null)
                return kycResult;

            var clientId = this.GetClientId();

            var viewModel = new AssetsExchangeIndexViewModel
            {
                Accounts = await _accountsRepository.GetAccountsAsync(clientId)
            };

            return View(viewModel);
        }
    }

}

LykkeWallet/Areas/Kyc/Controllers/PageController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Kyc;
using LykkeWallet.Areas.Kyc.Models;
using LykkeWallet.Controllers;

namespace LykkeWallet.Areas.Kyc.Controllers
{
    [Authorize]
    public class PageController : Controller
    {
        private readonly IKycRepository _kycRepository;

        public PageController(IKycRepository kycRepository)
        {
            _kycRepository = kycRepository;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var clientId = this.GetClientId();

            var viewModel = new KycIndexPageViewModel
            {
                KycStatus = await _kycRepository.GetKycStatusAsync(clientId)
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> GetKycStatus()
        {
            var clientId = this.GetClientId();

            var kycStatus = await _kycRepository.GetKycStatusAsync(clientId);

            return Json(new {approved = kycStatus == KycStatus.Ok});
        }
    }
}

LykkeWallet/Controllers/AccountsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Common;
using Core.Clients;
using LkeServices.Clients;
using LykkeWallet.Models;
using LykkeWallet.Strings;

namespace LykkeWallet.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientAccountsRepository _tradersRepository;
        private readonly SrvClientManager _srvClientManager;

        public ClientController(IClientAccountsRepository tradersRepository, SrvClientManager srvClientManager)
        {
            _tradersRepository = tradersRepository;
            _srvClientManager = srvClientManager;
        }

        [HttpPost]
        public ActionResult SignInDialog()
        {
            var viewModel = new SignInDialogViewModel
            {
                Email = this.GetCookie(ControllerExt.EmailCookie)
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult SignUpDialog(string email)
        {
            var viewModel = new SignUpViewModel
            {
                Email = email
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> SignIn(SignInModel model)
        {

            if (string.IsNullOrEmpty(model.Email))
                return this.JsonFailResult("#email", Phrases.FieldShouldNotBeEmpty);

            if (!model.Email.IsValidEmail())
                return this.JsonFailResult("#email", Phrases.PleaseTypeEmailHere);

            if (string.IsNullOrEmpty(model.Password))
                return this.JsonFailResult("#password", Phrases.FieldShouldNotBeEmpty);


            var trader = await _tradersRepository.AuthenticateAsync(model.Email, model.Password);

            if (trader == null)
                return this.JsonFailResult("#password", Phrases.InvalidUsernameOrPassword);

            this.AuthenticateUserViaOwin(trader);


            return GetAuthenticatedJsonResult();
        }

        [HttpPost]
        public async Task<ActionResult> SignUp(SignUpModel model)
        {

            if (string.IsNullOrEmpty(model.Email))
                return this.JsonFailResult("#email", Phrases.FieldShouldNotBeEmpty);

            if (!model.Email.IsValidEmail())
                return this.JsonFailResult("#email", Phrases.PleaseTypeEmailHere);


            if (await _tradersRepository.IsTraderWithEmailExistsAsync(model.Email))
                return this.JsonFailResult("#email", Phrases.UserWithEmalExists);

            if (string.IsNullOrEmpty(model.Password))
                return this.JsonFailResult("#password", Phrases.FieldShouldNotBeEmpty);


            if (string.IsNullOrEmpty(model.PasswordAgain))
                return this.JsonFailResult("#passwordAgain", Phrases.FieldShouldNotBeEmpty);

            if (model.Password != model.PasswordAgain)
                return this.JsonFailResult("#passwordAgain", Phrases.PasswordDoesNotMatch);

            if (string.IsNullOrEmpty(model.Phone))
                return this.JsonFailResult("#phone", Phrases.FieldShouldNotBeEmpty);

            var trader = await _srvClientManager.RegisterClientAsync(model.Email, model.FirstName, model.LastName, model.Password, model.Password);

            this.AuthenticateUserViaOwin(trader);

            return GetAuthenticatedJsonResult();
        }

        [HttpPost]
        public ActionResult SignOut()
        {
            this.SignUserOut();
            return this.JsonRefreshRoot();
        }

        private JsonResult GetAuthenticatedJsonResult()
        {

            if (Request.Browser.IsMobileDevice)
                return this.JsonShowContentResult("#pamain", Url.Action("Index", "IdentityVerification"), null, new JsonResultExtParams { ShowLoading = true });

            return this.JsonShowContentResult("body", Url.Action("Index", "IdentityVerification"), null, new JsonResultExtParams { ShowLoading = true });
        }

    }
}

LykkeWallet/Controllers/WalletController.cs
using System.Web.Mvc;

namespace LykkeWallet.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        [HttpPost]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetMenu()
        {
            return View();
        }

    }
}

LykkeWallet/Views/Wallet/GetMenu.cshtml
@using LykkeWallet.Strings
@model dynamic

@{
    Layout = null;
}

<div id="mnuAccounts" class="menu-item" onclick="wallet.selectPage('@Url.Action("Index","List", new {area="Accounts"})', '#mnuAccounts')">
    <table>
        <tr>
            <td>
                <img class="img" src="~/Images/Icons/safe.png"/>
            </td>
            <td>
                <div class="menu-title">@Phrases.Accounts</div>
            </td>
        </tr>
    </table>
</div>

<div id="mnuExchange" class="menu-item" onclick="wallet.selectPage('@Url.Action("Index","Assets", new {area="Exchange"})', '#mnuExchange')">
    <table>
        <tr>
            <td>
                <img class="img" src="~/Images/Icons/exchange.png" />
            </td>
            <td>
                <div class="menu-title">@Phrases.Trading</div>
            </td>
        </tr>
    </table>
</div>

<div id="mnuSettins" class="menu-item" onclick="wallet.selectPage('@Url.Action("Index","Page", new {area="Settings"})', '#mnuSettins')">
    <table>
        <tr>
            <td>
                <img class="img" src="~/Images/Icons/Settings.png" />
            </td>
            <td>
                <div class="menu-title">@Phrases.Settings</div>
            </td>
        </tr>
    </table>
</div>


<div id="mnuSignOut" class="menu-item" onclick="requests.doRequest({url:'@Url.Action("SignOut","Client")'})">
    <table>
        <tr>
            <td>
                <img class="img" src="~/Images/Icons/logout.png"/>
            </td>
            <td>
                <div class="menu-title">@Phrases.SignOut</div>
            </td>
        </tr>
    </table>
</div>

<script>
    wallet.selectPage('@Url.Action("Index","List", new {area="Accounts"})', '#mnuAccounts')
</script>

LykkeWallet/Views/Wallet/Index.cshtml
@model dynamic

<script>
    $('#btnMnu').show();
    requests.doRequest({ url: '@Url.Action("GetMenu")', divResult: '#mnuContent' });
</script>